# Helpers
_has() { whence -p "$1" >/dev/null 2>&1 }

# Prompt
if _has starship; then
    eval "$(starship init zsh)"
else
    PROMPT='%B%F{green}%n@%m%f %F{blue}%1~%f %# %b'
fi

# History
HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history
setopt appendhistory incappendhistory sharehistory
setopt histignorealldups histignorespace histreduceblanks

# Keybindings
bindkey -e

# Completion
autoload -Uz compinit
_zsh_cache="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
[[ -d "$_zsh_cache" ]] || mkdir -p "$_zsh_cache"
compinit -d "$_zsh_cache/zcompdump"
unset _zsh_cache

autoload -Uz colors
colors

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=long
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Colors
if _has dircolors; then
  eval "$(dircolors -b)"
  zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
elif [[ -n "$LS_COLORS" ]]; then
  zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
else
  export CLICOLOR=1
  zstyle ':completion:*:default' list-colors ''
fi

# Aliases
if _has eza; then
  alias ls='eza --color=auto'
elif _has dircolors; then
  alias ls='ls --color'
fi

_has nvim && alias vim='nvim'
_has bat && alias cat='bat'

# fzf
if _has fzf; then
  autoload -Uz is-at-least
  fzf_version="${$(fzf --version)%% *}"

  if is-at-least 0.48.0 "$fzf_version"; then
    source <(fzf --zsh)
  elif [[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]]; then
    source /usr/share/doc/fzf/examples/key-bindings.zsh
  fi

  unset fzf_version
fi

# zoxide
_has zoxide && eval "$(zoxide init zsh --cmd cd)"

# Syntax highlighting
if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
