# Helpers
_has() { whence -p "$1" >/dev/null 2>&1 }

# Prompt
if _has starship; then
    eval "$(starship init zsh)"

    # Starship does not currently provide native zsh transience. These zle hooks
    # redraw the just-submitted prompt as only Starship's character module, then
    # restore the full prompt before the next command line starts.
    _starship_full_prompt=$PROMPT
    _starship_full_rprompt=$RPROMPT

    _starship_transient_prompt() {
        PROMPT="$(starship module character)"
        RPROMPT=""
        zle .reset-prompt
    }

    _starship_restore_prompt() {
        PROMPT=$_starship_full_prompt
        RPROMPT=$_starship_full_rprompt
        zle .reset-prompt
    }

    zle -N zle-line-finish _starship_transient_prompt
    zle -N zle-line-init _starship_restore_prompt
else
    PROMPT='%B%F{green}%n@%m%f %F{blue}%1~%f %# %b'
fi

# History
HISTSIZE=50000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory incappendhistory sharehistory
setopt histignorealldups histsavenodups histfindnodups histignorespace histreduceblanks

# Keybindings
bindkey -e

# Completion
autoload -Uz compinit
_zsh_cache="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
[[ -d "$_zsh_cache" ]] || mkdir -p "$_zsh_cache"
compinit -d "$_zsh_cache/zcompdump"

autoload -Uz colors
colors

zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path "$_zsh_cache"
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes
zstyle ':completion:*' format '%F{blue}%d%f'
zstyle ':completion:*:descriptions' format '%F{yellow}%d%f'
zstyle ':completion:*:messages' format '%F{purple}%d%f'
zstyle ':completion:*:warnings' format '%F{red}No matches for: %d%f'
zstyle ':completion:*' matcher-list \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=* l:|=*'

zstyle ':completion:*:*:kill:*:processes' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

unset _zsh_cache

# Colors
if _has vivid; then
  export LS_COLORS="$(vivid generate catppuccin-mocha)"
elif _has dircolors; then
  eval "$(dircolors -b)"
else
  export CLICOLOR=1
fi

[[ -n "$LS_COLORS" ]] && zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Aliases
if _has eza; then
  alias ls='eza --color=auto --icons=auto'
  alias ll='eza -la --color=auto --icons=auto --git'
  alias tree='eza --tree --color=auto --icons=auto'
elif _has dircolors; then
  alias ls='ls --color'
fi

_has nvim && alias vim='nvim'
_has bat && alias cat='bat'

# fzf
if _has fzf; then
  autoload -Uz is-at-least
  fzf_version="${$(fzf --version)%% *}"

  if is-at-least 0.48.0 "$fzf_version"; then
    source <(fzf --zsh)
  elif [[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]]; then
    source /usr/share/doc/fzf/examples/key-bindings.zsh
  fi

  unset fzf_version
fi

# zoxide
_has zoxide && eval "$(zoxide init zsh --cmd cd)"

# Syntax highlighting
if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
